# Generated by Django 5.2.3 on 2025-06-28 21:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('reference_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='Display nickname for the client.', max_length=100, unique=True)),
                ('handle', models.CharField(help_text='Unique handle (like @user) for the client.', max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='commission',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='client_name',
        ),
        migrations.AddField(
            model_name='commission',
            name='type',
            field=models.CharField(choices=[('sketch', 'Sketch'), ('animation', 'Animation'), ('full', 'Full Illustration'), ('other', 'Other')], default='sketch', max_length=20),
        ),
        migrations.AlterField(
            model_name='commission',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='commission',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='commissions', to='commissions.character'),
        ),
        migrations.AddField(
            model_name='character',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='commissions.client'),
        ),
        migrations.AddField(
            model_name='commission',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='commissions.client'),
        ),
        migrations.AddField(
            model_name='commission',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='commissions', to='commissions.tag'),
        ),
    ]
